---

# We need sudo for some of the Docker commands.
sudo: required

services: 
  - docker

env:
  - distro: ubuntu1604

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test script
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests
  - ${PWD}/tests/test.sh

  # Ensure users were created. 
  - |
    'docker exec --tty ${container_id} env TERM=xterm user_exists=$(id -u deploy_test_1 > /dev/null 2>&1); \
    if [ $user_exists -eq 0 ]; then \
      echo "true"; \
    else \
      echo "false"; \
    fi' 
  # - 'docker exec --tty ${container_id} env TERM=xterm id -u deploy_test_2 > /dev/null 2>&1' 
