---

# We need sudo for some of the Docker commands.
sudo: required

services: 
  - docker

env:
  - distro: ubuntu1604

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test script
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  
  # Add execute privileges to all script files that will be run
  - chmod +x ${PWD}/tests/test.sh
  - chmod +x ${PWD}/tests/users_exist.sh
  - chmod +x ${PWD}/tests/users_sudo.sh

  # Run tests
  - ${PWD}/tests/test.sh

  # Ensure users were created. 
  - docker exec --tty ${container_id} env TERM=xterm /bin/bash /etc/ansible/roles/role_under_test/tests/users_exist.sh

  # Check users' sudo privileges
  - docker exec --tty ${container_id} env TERM=xterm /bin/bash /etc/ansible/roles/role_under_test/tests/users_sudo.sh
