---

- name: Sudo Group | Ensure sudo group is present
  group:
    name: sudo
    state: present

- name: Sudo Group | Ensure sudo group has sudo privileges
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "{{ (enable_passwordless_sudo) | ternary('%sudo ALL=(ALL) NOPASSWD:ALL', '%sudo ALL=(ALL:ALL) ALL') }}"
    validate: "visudo -cf %s" 

- name: Users | Create users
  user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    groups: "{{ item.groups | d(omit) }}" 
    append: "{{ item.append | d(omit) }}" 
    shell: "{{ item.shell | d(users_default_shell) }}" 
    update_password: "{{ item.update_password | d(omit) }}" 
    createhome: "{{ item.create_home_dir | d(omit) }}" 
    home: "{{ item.home | d(omit) }}" 
    state: present
  with_items: "{{ users }}"
  when: item.ssh_keys is defined
  no_log: true

- name: SSH Keys | Add authorized ssh key (public key) for users
  authorized_key:
    user: "{{ item.0.username }}"
    key: "{{ lookup('file', item.1) }}" 
  with_subelements:
    - "{{ users }}"
    - ssh_keys | d([])
    - skip_missing: yes
  no_log: true


