---

- name: Ensure sudo group is present
  group:
    name: sudo
    state: present

- name: Ensure sudo group has sudo privileges
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "{{ (enable_passwordless_sudo) | ternary('%sudo ALL=(ALL) NOPASSWD:ALL', '%sudo ALL=(ALL:ALL) ALL') }}" #"%sudo ALL=(ALL) NOPASSWD:ALL" 
    validate: "visudo -cf %s" 

- name: Create deploy user
  user:
    name: "{{ deploy_username }}"
    password: "{{ deploy_password }}"
    groups: 
      - sudo
    append: yes
    shell: /bin/bash
    update_password: always
    state: present

- name: Add authorized ssh key (public key) for deploy user
  authorized_key:
    user: "{{ deploy_username }}"
    key: "{{ lookup('file', {{ public_key }}) }}"